Neyberson/logistro
geopozo/logistro pull request #1
Opened 2024-11-19 15:19 UTC by neyberson

2024-12-03 15:55 UTC, ayjayt requested changes
- [x] Revisa `argparse`: que pasará si el usuario también usa el mismo paquete

También me parece un poco asimétrico que no haya `print_human` y `print_structured`

Tenemos que ser más claro con las partes del paquete que son:

Envolver `logging` para tener funciones más convenientes
Envolver `logging` para inicializar las cosas

Sorry, I forgot to write in english.

I don't want you to do all this work, I also have to put this up with ruff and circle CI, so I would like you to do parts of this, and then mark in the PR which parts I will do and I will create a separate PR.

2024-12-03 15:55 UTC, ayjayt commented on logistro/custom_logging.py
> +        names = [handler.stream.name for handler in logger.handlers]
oof que esta pasando

2024-12-03 16:53 UTC, neyberson commented on logistro/custom_logging.py
> +handler = logging.StreamHandler(stream=sys.stderr)
Sin eso, no fuciona, lo probé varias veces desde la primera vez que hice custom_logging.py en Baile

2024-12-03 19:35 UTC, neyberson commented on logistro/custom_logging.py
> +logger.propagate = False
[https://docs.python.org/3/library/logging.html#logging.Logger.propagate](url)

2024-12-03 21:20 UTC, neyberson commented on logistro/custom_logging.py
> +def customize_parser(add_help=False):
Este es porque los usuarios que van a usar argparse, deben usar `customize_parser()`, para generar un parser que ya tenga las opciones de `--human` y `--structured`. Busqué muchas soluciones y opciones y esta fue la única a la que pude llegar, también la más sencilla. No sé si haya alguna otra forma más complicada
I will add the prefix and the error

2024-12-04 14:53 UTC, neyberson commented on logistro/__init__.py
> +    "critical",
pues yo creo que sí, porque es lo que se usa de logistro, algunos son para inicializar, otros para customizar y otros para hacer los logs

2024-12-04 14:54 UTC, neyberson commented on logistro/custom_logging.py
> +basicConfig = logging.basicConfig
es para agregar el nivel customizado de DEBUG2

2024-12-04 14:55 UTC, ayjayt commented
In get_context_info
a) `where uses` is not proper english
    proper english examples:
    `gets the module using logistro`
   `gets the module calling logistro`
   `gets the module where logistro is used`
b) please write comments more explicitly explaining what you are doing, why are you going back 3 frames? 4 frames? It is very unclear.
c) `module_frame = inspect.getmodule(upper_frame) or inspect.getmodule(upper_frame.f_back)` what is going on here?

2024-12-04 15:05 UTC, neyberson commented on logistro/custom_logging.py
> +def _print_structured(
esa es la función que hace el log de `--logistro_structured`

2024-12-04 17:24 UTC, neyberson commented on logistro/custom_logging.py
> +        names = [handler.stream.name for handler in logger.handlers]
eso solamente es para que verifique si el `stream_output` que podría dar el usuario está o no en los handlers del logger

2024-12-25 14:44 UTC, merged